# Generated by Django 5.0 on 2023-12-13 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(help_text='Номер поїзда', max_length=10, unique=True)),
                ('departure_station', models.CharField(help_text='Станція відправлення', max_length=100)),
                ('arrival_station', models.CharField(help_text='Станція призначення', max_length=100)),
                ('departure_time', models.DateTimeField(help_text='Час відправлення')),
                ('arrival_time', models.DateTimeField(help_text='Час прибуття')),
                ('total_seats', models.PositiveIntegerField(help_text='Загальна кількість місць у поїзді')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Номер місця', max_length=5)),
                ('is_booked', models.BooleanField(default=False, help_text='Статус бронювання')),
                ('train', models.ForeignKey(help_text='Поїзд', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='Seats.train')),
            ],
            options={
                'unique_together': {('train', 'seat_number')},
            },
        ),
    ]
